### ISSUE TITLE
Bug: When creating a caption for a GIF file, the script finishes but it does not make a new GIF

### ISSUE THREAD

**Issue by clearlakes** [kubinka0505/iFunny-Captions#2]
From what I can tell from the console output, it seems like something did not work during the `Making GIF...` phase

**Used `iFunny-Captions` Version:** 2.9
**Image URL:** https://tenor.com/Fuiq.gif
^ When I added a local file path to the config file, it gave me the following error, so I used a URL instead:
`requests.exceptions.MissingSchema: Invalid URL 'Images/file.gif': No schema supplied. Perhaps you meant http://Images/file.gif?`

**FFmpeg Version (do not input when You made Your own build):** 4.3.2
**Console Log (after running `python3 __init__.pyw`):**
```
Setting up utils...
URL was located in cache folder!
Copying files to main directory...
Making GIF...
Saving GIF...
gifsicle: Images/Example_X6jwNC0j.gif: No such file or directory
Optimizing...
gifsicle: Images/Example_X6jwNC0j.gif: No such file or directory
Removing Frames...
Done!

Modules were loaded in:			00:00.262396.
Input URL was converted to frames in:	00:00.000173.
Frames were processed in:		00:00.000001.
GIF was made in:			00:00.259277.
Frames were deleted in:			00:00.000261.
All operations were done in:		00:00.522108.
```
In case it might be a factor, the OS I'm running is Ubuntu 18.04.5 LTS

**Comment by kubinka0505** [comment]
This issue is caused in the `Scripts/Utils.pyw`, where I didn't add `//` on the tenor and Giphy URLs.
This will be fixed in the next release.

For now, you can wait, or add `//` to the strings in lines `14` and `15` in this file:
From:
```python
	if "tenor.com/view" in URL:
	if "giphy.com/gifs" in URL:
```
To:
```python
	if "//tenor.com/view" in URL:
	if "//giphy.com/gifs" in URL:
```
Furthermore, I would recommend using full image hosting services URLs, like:
- `https://tenor.com/Fuiq.gif` ❌
- `https://tenor.com/view/toons-homer-the-simpsons-walking-in-circle-gif-7465560` ✔️

**Comment by clearlakes** [comment]
Thanks for the response, however I've edited the lines of code (as well as used the full URL like you said) and it still fails to create a new file (and continues to give a `requests.exceptions.MissingSchema` error if I use a file path; I might be wrong but I think it has something to do with how the path is handled in the Error Handling section of `__init__.pyw`)

There also could be something OS-specific about these errors, as I've tried the program on a Windows 10 machine and it seems to work perfectly. As you have said, I'll wait for the newer updates to see if anything has changed. Thanks again

**Comment by raku-cat** [comment]
Can confirm it fails in the exact same way for me using a local file (put in config as `file:///path/to/file.gif`)

Appears to be caused by a bug at: https://github.com/kubinka0505/iFunny-Captions/blob/246616353b13839ad4863d4b4b67a88d5434714e/__init__.pyw#L191-L192
**Frame_%06d.png** here should be  **Frame_%05d.png** as they are generated earlier in the script. 
If you set the ffmpeg loglevel a little higher you'll get the "file not found" errors pointing this out.

~~However, even with this update, for me at least, it completes and generates an image but no caption is added.~~
Edit: Something I did during debugging broke some part, I reset and did only the edit of `06d` to `05d` as mentioned and all systems are go.

**Comment by kubinka0505** [comment]
> 
> Can confirm it fails in the exact same way for me using a local file (put in config as `file:///path/to/file.gif`)
> 
> Appears to be caused by a bug at:
> 
> https://github.com/kubinka0505/iFunny-Captions/blob/246616353b13839ad4863d4b4b67a88d5434714e/__init__.pyw#L191-L192
> 
> **Frame_%06d.png** here should be **Frame_%05d.png** as they are generated earlier in the script.
> If you set the ffmpeg loglevel a little higher you'll get the "file not found" errors pointing this out.
> 
> ~However, even with this update, for me at least, it completes and generates an image but no caption is added.~
> Edit: Something I did during debugging broke some part, I reset and did only the edit of `06d` to `05d` as mentioned and all systems are go.


Either this is a string parsing error that I've made, or it is OS dependent - I could make an operating system at the expense of elegance to enable wildcards [that are not applied by default compiled versions on FFmpeg for Windows](http://stackoverflow.com/q/31513542), (I assume that you are using Windows) or make new name formatting system.

**Comment by raku-cat** [comment]
I am on Arch Linux with the ffmpeg provided by my package manager.

I don't know that this is the same issue as you think it is, earlier in the script as I mentioned you explicitly save these using `05d`
https://github.com/kubinka0505/iFunny-Captions/blob/246616353b13839ad4863d4b4b67a88d5434714e/__init__.pyw#L111
And the frames are saved properly (5 digit positions):
![image](https://user-images.githubusercontent.com/1125449/115568557-077cce00-a282-11eb-83e1-0d5b167f1337.png)

You are then accessing these later in the script as I linked above, with the glob of `06d`:
https://github.com/kubinka0505/iFunny-Captions/blob/246616353b13839ad4863d4b4b67a88d5434714e/__init__.pyw#L191-L192
So that step fails, as no such file exists.

Should be noted the "Required files" link here:
![image](https://user-images.githubusercontent.com/1125449/115568027-80c7f100-a281-11eb-9f72-c2cb5dfafbf1.png)
Is a dead link, so I just skipped it, didn't realize I had to compile or download an older binary and place it in the location of the script, and things worked fine without me doing this.

**Comment by kubinka0505** [comment]
> I am on Arch Linux with the ffmpeg provided by my package manager.
> 
> I don't know that this is the same issue as you think it is, earlier in the script as I mentioned you explicitly save these using `05d`
> https://github.com/kubinka0505/iFunny-Captions/blob/246616353b13839ad4863d4b4b67a88d5434714e/__init__.pyw#L111
> And the frames are saved properly (5 digit positions):
> ![image](https://user-images.githubusercontent.com/1125449/115568557-077cce00-a282-11eb-83e1-0d5b167f1337.png)
> 
> You are then accessing these later in the script as I linked above, with the glob of `06d`:
> https://github.com/kubinka0505/iFunny-Captions/blob/246616353b13839ad4863d4b4b67a88d5434714e/__init__.pyw#L191-L192
> So that step fails, as no such file exists.
> 
> Should be noted the "Required files" link here:
> ![image](https://user-images.githubusercontent.com/1125449/115568027-80c7f100-a281-11eb-9f72-c2cb5dfafbf1.png)
> Is a dead link, so I just skipped it, didn't realize I had to compile or download an older binary and place it in the location of the script, and things worked fine without me doing this.

Well, this is more complicated than I thought... If I could build FFmpeg with wildcards, (`%nd` is not a glob, **it's a sequence**) I'd probably manage to fix it somehow.
Thanks for the dead link reference, I got to replace that soon.
You do not have to replace Your current FFmpeg package, its version just needs to be **higher or equal** to provided in `ReadMe.md`.

_In version 3.0 there will be `Debug` key in `Config.json` which will enable all programs output in verbose mode._

Maybe I could figure the solution out if you could post full FFmpeg tracebacks by removing loglevel arguments in `os.system` commands - if you know how.

**Comment by raku-cat** [comment]
I'm not sure what problem you're encountering? You have the arguments for ffmpeg written  incorrectly, the frames are created with a command that creates them with 5 digit positions and then they're read with a command that expects 6, and so ffmpeg can't find them.  I'm not sure why or how this would behave any differently on your system or any system.
L#111 either needs to be changed to `%06d` or L#191 and L#192 need to be changed to `%05d`.
